import { Audio } from 'src/RadicalTypes';

export const audioListSeason1 = [
  {
    firstSongName: 'The Encryption',
    firstSongArtist: 'Au5 feat. Kenny Raye and Nasty Purple',
    firstSongLink: 'https://www.youtube-nocookie.com/embed/LcB-HGpKtUo',
    secondSongName: 'Enigma of Abode',
    secondSongArtist: 'Disperse',
    secondSongLink: 'https://www.youtube.com/embed/C2SkoVmmVas',
    thirdSongName: 'Little Snakes',
    thirdSongArtist: 'Protest The Hero',
    thirdSongLink: 'https://www.youtube-nocookie.com/embed/OXyb5tDR8RA',
  },
  {
    firstSongName: 'Proto Cosmos',
    firstSongArtist: 'Tony Williams',
    firstSongLink: 'https://www.youtube-nocookie.com/embed/o2tKA5IfCWA',
    secondSongName: 'Proto Cosmos',
    secondSongArtist: 'Greg Howe, Dennis Chambers, Victor Wooten',
    secondSongLink: 'https://www.youtube-nocookie.com/embed/hvg1zoRacHQ',
    thirdSongName: 'La Ovega Negra',
    thirdSongArtist: 'Silvio Rodriguez',
    thirdSongLink: 'https://www.youtube-nocookie.com/embed/8Rl30GaTZRg',
  },
  {
    firstSongName: 'The Way I feel',
    firstSongArtist: 'Remy Shand',
    firstSongLink: 'https://www.youtube-nocookie.com/embed/wf6GbW82VcQ',
    secondSongName: 'So Complicated',
    secondSongArtist: 'God Made Me Funky',
    secondSongLink: 'https://www.youtube-nocookie.com/embed/5M1RESvRrrA',
    thirdSongName: 'Zizojika Izinto',
    thirdSongArtist: 'Economic Freedom Fighters',
    thirdSongLink: 'https://www.youtube-nocookie.com/embed/Mp-KiQ-Cy0A',
  },
  {
    firstSongName: 'Where Are The Birds?',
    firstSongArtist: 'Good Tiger',
    firstSongLink: 'https://www.youtube-nocookie.com/embed/LcB-HGpKtUo',
    secondSongName: 'One Hand Killing',
    secondSongArtist: 'Twelve Foot Ninja',
    secondSongLink: 'https://www.youtube-nocookie.com/embed/xiVFQwMHmKs',
    thirdSongName: 'Alone Again Or',
    thirdSongArtist: 'Love',
    thirdSongLink: 'https://www.youtube-nocookie.com/embed/cPbNpIG8x_s',
  },
  {
    firstSongName: 'The Encryption',
    firstSongArtist: 'Au5 feat. Kenny Raye and Nasty Purple',
    firstSongLink: 'https://www.youtube-nocookie.com/embed/LcB-HGpKtUo',
    secondSongName: 'Enigma of Abode',
    secondSongArtist: 'Disperse',
    secondSongLink: 'https://www.youtube.com/embed/C2SkoVmmVas',
    thirdSongName: 'Little Snakes',
    thirdSongArtist: 'Protest The Hero',
    thirdSongLink: 'https://www.youtube-nocookie.com/embed/OXyb5tDR8RA',
  },
  {
    firstSongName: 'The Encryption',
    firstSongArtist: 'Au5 feat. Kenny Raye and Nasty Purple',
    firstSongLink: 'https://www.youtube-nocookie.com/embed/LcB-HGpKtUo',
    secondSongName: 'Enigma of Abode',
    secondSongArtist: 'Disperse',
    secondSongLink: 'https://www.youtube.com/embed/C2SkoVmmVas',
    thirdSongName: 'Little Snakes',
    thirdSongArtist: 'Protest The Hero',
    thirdSongLink: 'https://www.youtube-nocookie.com/embed/OXyb5tDR8RA',
  },
  {
    firstSongName: 'The Encryption',
    firstSongArtist: 'Au5 feat. Kenny Raye and Nasty Purple',
    firstSongLink: 'https://www.youtube-nocookie.com/embed/LcB-HGpKtUo',
    secondSongName: 'Enigma of Abode',
    secondSongArtist: 'Disperse',
    secondSongLink: 'https://www.youtube.com/embed/C2SkoVmmVas',
    thirdSongName: 'Little Snakes',
    thirdSongArtist: 'Protest The Hero',
    thirdSongLink: 'https://www.youtube-nocookie.com/embed/OXyb5tDR8RA',
  },
  {
    firstSongName: 'The Encryption',
    firstSongArtist: 'Au5 feat. Kenny Raye and Nasty Purple',
    firstSongLink: 'https://www.youtube-nocookie.com/embed/LcB-HGpKtUo',
    secondSongName: 'Enigma of Abode',
    secondSongArtist: 'Disperse',
    secondSongLink: 'https://www.youtube.com/embed/C2SkoVmmVas',
    thirdSongName: 'Little Snakes',
    thirdSongArtist: 'Protest The Hero',
    thirdSongLink: 'https://www.youtube-nocookie.com/embed/OXyb5tDR8RA',
  },
  {
    firstSongName: 'The Encryption',
    firstSongArtist: 'Au5 feat. Kenny Raye and Nasty Purple',
    firstSongLink: 'https://www.youtube-nocookie.com/embed/LcB-HGpKtUo',
    secondSongName: 'Enigma of Abode',
    secondSongArtist: 'Disperse',
    secondSongLink: 'https://www.youtube.com/embed/C2SkoVmmVas',
    thirdSongName: 'Little Snakes',
    thirdSongArtist: 'Protest The Hero',
    thirdSongLink: 'https://www.youtube-nocookie.com/embed/OXyb5tDR8RA',
  },
  {
    firstSongName: 'The Encryption',
    firstSongArtist: 'Au5 feat. Kenny Raye and Nasty Purple',
    firstSongLink: 'https://www.youtube-nocookie.com/embed/LcB-HGpKtUo',
    secondSongName: 'Enigma of Abode',
    secondSongArtist: 'Disperse',
    secondSongLink: 'https://www.youtube.com/embed/C2SkoVmmVas',
    thirdSongName: 'Little Snakes',
    thirdSongArtist: 'Protest The Hero',
    thirdSongLink: 'https://www.youtube-nocookie.com/embed/OXyb5tDR8RA',
  },
  {
    firstSongName: 'The Encryption',
    firstSongArtist: 'Au5 feat. Kenny Raye and Nasty Purple',
    firstSongLink: 'https://www.youtube-nocookie.com/embed/LcB-HGpKtUo',
    secondSongName: 'Enigma of Abode',
    secondSongArtist: 'Disperse',
    secondSongLink: 'https://www.youtube.com/embed/C2SkoVmmVas',
    thirdSongName: 'Little Snakes',
    thirdSongArtist: 'Protest The Hero',
    thirdSongLink: 'https://www.youtube-nocookie.com/embed/OXyb5tDR8RA',
  },
  {
    firstSongName: 'The Encryption',
    firstSongArtist: 'Au5 feat. Kenny Raye and Nasty Purple',
    firstSongLink: 'https://www.youtube-nocookie.com/embed/LcB-HGpKtUo',
    secondSongName: 'Enigma of Abode',
    secondSongArtist: 'Disperse',
    secondSongLink: 'https://www.youtube.com/embed/C2SkoVmmVas',
    thirdSongName: 'Little Snakes',
    thirdSongArtist: 'Protest The Hero',
    thirdSongLink: 'https://www.youtube-nocookie.com/embed/OXyb5tDR8RA',
  },
  {
    firstSongName: 'The Encryption',
    firstSongArtist: 'Au5 feat. Kenny Raye and Nasty Purple',
    firstSongLink: 'https://www.youtube-nocookie.com/embed/LcB-HGpKtUo',
    secondSongName: 'Enigma of Abode',
    secondSongArtist: 'Disperse',
    secondSongLink: 'https://www.youtube.com/embed/C2SkoVmmVas',
    thirdSongName: 'Little Snakes',
    thirdSongArtist: 'Protest The Hero',
    thirdSongLink: 'https://www.youtube-nocookie.com/embed/OXyb5tDR8RA',
  },
  {
    firstSongName: 'The Encryption',
    firstSongArtist: 'Au5 feat. Kenny Raye and Nasty Purple',
    firstSongLink: 'https://www.youtube-nocookie.com/embed/LcB-HGpKtUo',
    secondSongName: 'Enigma of Abode',
    secondSongArtist: 'Disperse',
    secondSongLink: 'https://www.youtube.com/embed/C2SkoVmmVas',
    thirdSongName: 'Little Snakes',
    thirdSongArtist: 'Protest The Hero',
    thirdSongLink: 'https://www.youtube-nocookie.com/embed/OXyb5tDR8RA',
  },
  {
    firstSongName: 'The Encryption',
    firstSongArtist: 'Au5 feat. Kenny Raye and Nasty Purple',
    firstSongLink: 'https://www.youtube-nocookie.com/embed/LcB-HGpKtUo',
    secondSongName: 'Enigma of Abode',
    secondSongArtist: 'Disperse',
    secondSongLink: 'https://www.youtube.com/embed/C2SkoVmmVas',
    thirdSongName: 'Little Snakes',
    thirdSongArtist: 'Protest The Hero',
    thirdSongLink: 'https://www.youtube-nocookie.com/embed/OXyb5tDR8RA',
  },
  {
    firstSongName: 'The Encryption',
    firstSongArtist: 'Au5 feat. Kenny Raye and Nasty Purple',
    firstSongLink: 'https://www.youtube-nocookie.com/embed/LcB-HGpKtUo',
    secondSongName: 'Enigma of Abode',
    secondSongArtist: 'Disperse',
    secondSongLink: 'https://www.youtube.com/embed/C2SkoVmmVas',
    thirdSongName: 'Little Snakes',
    thirdSongArtist: 'Protest The Hero',
    thirdSongLink: 'https://www.youtube-nocookie.com/embed/OXyb5tDR8RA',
  },
  {
    firstSongName: 'The Encryption',
    firstSongArtist: 'Au5 feat. Kenny Raye and Nasty Purple',
    firstSongLink: 'https://www.youtube-nocookie.com/embed/LcB-HGpKtUo',
    secondSongName: 'Enigma of Abode',
    secondSongArtist: 'Disperse',
    secondSongLink: 'https://www.youtube.com/embed/C2SkoVmmVas',
    thirdSongName: 'Little Snakes',
    thirdSongArtist: 'Protest The Hero',
    thirdSongLink: 'https://www.youtube-nocookie.com/embed/OXyb5tDR8RA',
  },
  {
    firstSongName: 'The Encryption',
    firstSongArtist: 'Au5 feat. Kenny Raye and Nasty Purple',
    firstSongLink: 'https://www.youtube-nocookie.com/embed/LcB-HGpKtUo',
    secondSongName: 'Enigma of Abode',
    secondSongArtist: 'Disperse',
    secondSongLink: 'https://www.youtube.com/embed/C2SkoVmmVas',
    thirdSongName: 'Little Snakes',
    thirdSongArtist: 'Protest The Hero',
    thirdSongLink: 'https://www.youtube-nocookie.com/embed/OXyb5tDR8RA',
  },
  {
    firstSongName: 'The Encryption',
    firstSongArtist: 'Au5 feat. Kenny Raye and Nasty Purple',
    firstSongLink: 'https://www.youtube-nocookie.com/embed/LcB-HGpKtUo',
    secondSongName: 'Enigma of Abode',
    secondSongArtist: 'Disperse',
    secondSongLink: 'https://www.youtube.com/embed/C2SkoVmmVas',
    thirdSongName: 'Little Snakes',
    thirdSongArtist: 'Protest The Hero',
    thirdSongLink: 'https://www.youtube-nocookie.com/embed/OXyb5tDR8RA',
  },
  {
    firstSongName: 'The Encryption',
    firstSongArtist: 'Au5 feat. Kenny Raye and Nasty Purple',
    firstSongLink: 'https://www.youtube-nocookie.com/embed/LcB-HGpKtUo',
    secondSongName: 'Enigma of Abode',
    secondSongArtist: 'Disperse',
    secondSongLink: 'https://www.youtube.com/embed/C2SkoVmmVas',
    thirdSongName: 'Little Snakes',
    thirdSongArtist: 'Protest The Hero',
    thirdSongLink: 'https://www.youtube-nocookie.com/embed/OXyb5tDR8RA',
  },
  {
    firstSongName: 'The Encryption',
    firstSongArtist: 'Au5 feat. Kenny Raye and Nasty Purple',
    firstSongLink: 'https://www.youtube-nocookie.com/embed/LcB-HGpKtUo',
    secondSongName: 'Enigma of Abode',
    secondSongArtist: 'Disperse',
    secondSongLink: 'https://www.youtube.com/embed/C2SkoVmmVas',
    thirdSongName: 'Little Snakes',
    thirdSongArtist: 'Protest The Hero',
    thirdSongLink: 'https://www.youtube-nocookie.com/embed/OXyb5tDR8RA',
  },
  {
    firstSongName: 'The Encryption',
    firstSongArtist: 'Au5 feat. Kenny Raye and Nasty Purple',
    firstSongLink: 'https://www.youtube-nocookie.com/embed/LcB-HGpKtUo',
    secondSongName: 'Enigma of Abode',
    secondSongArtist: 'Disperse',
    secondSongLink: 'https://www.youtube.com/embed/C2SkoVmmVas',
    thirdSongName: 'Little Snakes',
    thirdSongArtist: 'Protest The Hero',
    thirdSongLink: 'https://www.youtube-nocookie.com/embed/OXyb5tDR8RA',
  },
  {
    firstSongName: 'The Encryption',
    firstSongArtist: 'Au5 feat. Kenny Raye and Nasty Purple',
    firstSongLink: 'https://www.youtube-nocookie.com/embed/LcB-HGpKtUo',
    secondSongName: 'Enigma of Abode',
    secondSongArtist: 'Disperse',
    secondSongLink: 'https://www.youtube.com/embed/C2SkoVmmVas',
    thirdSongName: 'Little Snakes',
    thirdSongArtist: 'Protest The Hero',
    thirdSongLink: 'https://www.youtube-nocookie.com/embed/OXyb5tDR8RA',
  },
  {
    firstSongName: 'The Encryption',
    firstSongArtist: 'Au5 feat. Kenny Raye and Nasty Purple',
    firstSongLink: 'https://www.youtube-nocookie.com/embed/LcB-HGpKtUo',
    secondSongName: 'Enigma of Abode',
    secondSongArtist: 'Disperse',
    secondSongLink: 'https://www.youtube.com/embed/C2SkoVmmVas',
    thirdSongName: 'Little Snakes',
    thirdSongArtist: 'Protest The Hero',
    thirdSongLink: 'https://www.youtube-nocookie.com/embed/OXyb5tDR8RA',
  },
] as Audio[];

export const audioListSeason2 = [
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
] as Audio[];
